name: Tokyp Olympics data pre-process

on:
  workflow_dispatch

  env_vars: ""
  env_vars1: ""
  env_vars2: ""

# env:
#   accountName: ${{secret.ACCNT_NAME}}
#   containerName: ${{secret.CONT_NAME}}

 

  name: "Account_name"
  value: ""

  name: "Container_Name"
  value: ""
jobs:
  preProcessData:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: actions/checkout@v3
      
      - name: setup python
        run: actions/setup-python@v4

        with:
          python-version: '3.11'

      - name: Run python scrpit
        run: | 
          cd HttpTrigger1_tokyoOlympics
          pip3 install -r requirements.txt
          python3 app.py -aacnt_name $env_vars -accnt_key $env_vars1 -cont_name $env_vars2
              
